var section1 = [
  {
    "isQuestion": false,
    "id":"q15",
    "title": "Next section: Purpose",
    "paragraph":["Dolor debitis illo soluta mollitia aperiam explicabo perspiciatis. Sapiente ea consequatur aut et laboriosam ex a quaerat. Culpa voluptas dicta recusandae sequi vel nihil voluptas. Sed non qui est sed.", "Nihil eligendi alias omnis explicabo sint. Dolores voluptas aut quae cum. Vitae provident quibusdam dolorem molestiae. Est molestias et aut sequi repudiandae.","Repellat ut ut possimus voluptates et laboriosam tenetur. Quam cum deleniti harum necessitatibus. Consectetur ut voluptatem velit atque et numquam reiciendis vel. Rerum maxime eos tenetur. Est et ut asperiores aut."]
  },
  {
    "isQuestion": true,
    "id":"q16",
    "spaces":["e","p"],
    "position":["pu",1],
    "q":"Three words to describe the environment you’re committing to creating:",
    "required":false,
    "policyEntry":"This Code of Conduct is meant to support a [answers] space where participants are treated with dignity and are free to be themselves.",
    "answers":[
      {
        "type":"checkbox",
        "answerText":"respectful",
        "storeAs":"[env]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"friendly",
        "storeAs":"[env]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"professional",
        "storeAs":"[env]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"inclusive",
        "storeAs":"[env]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"collaborative",
        "storeAs":"[env]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"safe",
        "storeAs":"[env]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"productive",
        "storeAs":"[env]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"welcoming",
        "storeAs":"[env]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"happy",
        "storeAs":"[env]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"harassment-free",
        "storeAs":"[env]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other",
        "storeAs":"[env]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q17",
    "spaces":["e","p"],
    "position":["pu",2],
    "q":'Add to the sentence “this environment is for everyone regardless of their...”',
    "required":false,
    "policyEntry":"[name] is committed to providing a [env] environment for everyone, regardless of their [identities]",
    "answers":[
      {
        "type":"checkbox",
        "answerText":"gender identity & expression",
        "storeAs":"[identities]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"race & ethnicity",
        "storeAs":"[identities]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"socioeconomic status,",
        "storeAs":"[identities]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"religion (or lack thereof)",
        "storeAs":"[identities]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"sexual orientation & characteristics",
        "storeAs":"[identities]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"physical appearance",
        "storeAs":"[identities]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"ability",
        "storeAs":"[identities]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"age",
        "storeAs":"[identities]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other",
        "storeAs":"[identities]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":"Each of these are important Consider each as you add them manually."},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q18",
    "spaces":["e"],
    "position":["pu",3],
    "q":"Who does the Code of Conduct apply to?",
    "required":false,
    "policyEntry":"Individuals are responsible for knowing and abiding by our standards and we encourage everyone to assist in creating a welcoming and safe environment. This Code of Conduct outlines our expectations for [people] and all those who participate in our community.",
    "answers":[
      {
        "type":"checkbox",
        "answerText":"service providers",
        "storeAs":"[people]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"attendees",
        "storeAs":"[people]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"speakers",
        "storeAs":"[people]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"organizers",
        "storeAs":"[people]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other",
        "storeAs":"[people]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q19",
    "spaces":["p"],
    "position":["pu",3],
    "q":"Who does the Code of Conduct apply to?",
    "required":false,
    "policyEntry":"Individuals are responsible for knowing and abiding by our standards and we encourage everyone to assist in creating a welcoming and safe environment. This Code of Conduct outlines our expectations for [people] and all those who participate in our community.",
    "answers":[
      {
        "type":"checkbox",
        "answerText":"service providers",
        "storeAs":"[people]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"contributors",
        "storeAs":"[people]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"decision-makers",
        "storeAs":"[people]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other",
        "storeAs":"[people]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q20",
    "spaces":["off"],
    "position":["pu",4],
    "q":"Does this Code of Conduct apply in related social events?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"Yes",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"radio",
        "answerText":"No",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q21",
    "spaces":["off"],
    "position":["be",4],
    "q":"Is the venue shared with members of the public?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"Yes",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"radio",
        "answerText":"No",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q22",
    "spaces":["e","p"],
    "position":["sp",0],
    "q":"Does this Code of Conduct apply to sponsors?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"Yes",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"radio",
        "answerText":"No",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q23",
    "spaces":["e","p"],
    "position":["be",0],
    "q":"Specify behaviour that is unacceptable in your community:",
    "required":false,
    "policyEntry":"[name] has zero-tolerance for any form of discrimination or harassment, including but not limited to [behaviour]",
    "answers":[
      {
        "type":"checkbox",
        "answerText":"misgendering",
        "storeAs":"[behaviour]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"stalking",
        "storeAs":"[behaviour]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"incitement of violence",
        "storeAs":"[behaviour]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"outing",
        "storeAs":"[behaviour]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"doxxing",
        "storeAs":"[behaviour]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"posting abuse",
        "storeAs":"[behaviour]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"inappropriate filming or photography",
        "storeAs":"[behaviour]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"simulated & physical sexual harassment",
        "storeAs":"[behaviour]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"verbal abuse",
        "storeAs":"[behaviour]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other",
        "storeAs":"[behaviour]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":"Harassing recording includes logging online activity for harassment purposes."},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q24",
    "spaces":["off"],
    "position":["be",1],
    "q":"Any additional unacceptable behaviour",
    "required":false,
    "policyEntry":"[behaviour-add] are also not welcome at [name].",
    "answers":[
      {
        "type":"checkbox",
        "answerText":"weapons",
        "storeAs":"[behaviour-add]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"drugs",
        "storeAs":"[behaviour-add]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"drugging",
        "storeAs":"[behaviour-add]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q25",
    "spaces":["e"],
    "position":["fp",0],
    "q":"Will there be official filming and/or photography?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"filming",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"There will be official filming taking place during [name].",
      },
      {
        "type":"radio",
        "answerText":"photography",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"There will be official photography taking place during [name].",
      },
      {
        "type":"radio",
        "answerText":"both",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"There will be official filming and photography taking place during [name].",
      },
      {
        "type":"radio",
        "answerText":"No",
        "storeAs": "",
        "excludes":[26,27,28,29],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q26",
    "spaces":["e"],
    "position":["fp",1],
    "q":"Where will the filming take place?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"Breakout rooms",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"The [media] will be focused on the breakout rooms.",
      },
      {
        "type":"radio",
        "answerText":"Whole event",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"The [media] will be happening throughout the event.",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other",
        "storeAs":"[other-media]",
        "excludes":[],
        "includes":[],
        "policyEntry":"[other-media]",
      },
    ],
    "tips":[
      {"meaning":"Not everyone wants to be on camera or used in promotional material, so make it clear how much recording and photography they can expect"},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q27",
    "spaces":["e"],
    "position":["fp",2],
    "q":"What happens to the recordings or photos?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"checkbox",
        "answerText":"deleted after transcription",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"Recordings are made to enable us to transcribe the video in order to capture the arguments being presented. The recordings will be deleted once the transcription is completed.",
      },
      {
        "type":"checkbox",
        "answerText":"attribution with consent",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"Attributions to individuals for their comments will not be made without their explicit permission.",
      },
      {
        "type":"checkbox",
        "answerText":"not shared with others",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"Neither photos nor recordings are not passed on to any third party. They are only viewed by the [name] team.",
      },
      {
        "type":"checkbox",
        "answerText":"used in promotional materials",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"Recordings and photos may be used in future [name] promotional content.",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other uses",
        "storeAs":"[other-uses]",
        "excludes":[],
        "includes":[],
        "policyEntry":"[other-uses]",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q28",
    "spaces":["off"],
    "position":["fp",3],
    "q":"Can attendees opt-out of being photographed or filmed in-person at your event?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"Lanyard color denotes consent",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"During the [name] event, attendees can express their consent to being filmed and photography through the colour of their lanyard, selected upon entry.",
      },
      {
        "type":"radio",
        "answerText":"No",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":"Avoid relying solely on lanyard color to denote consent as this can be troublesome for those with visual impairments."},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q29",
    "spaces":["on"],
    "position":["fp",4],
    "q":"Can attendees opt-out of having their online participation recorded?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"Turn off camera",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"Participants can opt-out of having their online participation recorded by keeping their camera switched off.",
      },
      {
        "type":"radio",
        "answerText":"No",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q30",
    "spaces":["on","c"],
    "position":["et",0],
    "q":"Are participants discouraged from sending unsolicited direct messages to each other?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"Yes",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"In this community we encourage public discussion and respect each others’ space, therefore we ask that you refrain from sending unsolicited direct messages to others participants.",
      },
      {
        "type":"radio",
        "answerText":"No",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q31",
    "spaces":["p"],
    "position":["et",1],
    "q":"Which commercial posts are not permitted?",
    "required":false,
    "policyEntry":"Please do not leave commercial posts on the [name] [type]. This includes [commercials]",
    "answers":[
      {
        "type":"checkbox",
        "answerText":"adverts",
        "storeAs":"[commercials]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"self-promotion",
        "storeAs":"[commercials]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"sales pitches",
        "storeAs":"[commercials]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"spam",
        "storeAs":"[commercials]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"affiliate links",
        "storeAs":"[commercials]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other",
        "storeAs":"[commercials]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q32",
    "spaces":["on"],
    "position":["ch",1],
    "q":"Which commercial posts are allowed in the chat?",
    "required":false,
    "policyEntry":"The [name] chat functionality is for attendees to engage with the conference. Please do not leave commercial posts, including [chat-ads].",
    "answers":[
      {
        "type":"checkbox",
        "answerText":"adverts",
        "storeAs":"[chat-ads]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"self-promotion",
        "storeAs":"[chat-ads]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"sales pitches",
        "storeAs":"[chat-ads]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"spam",
        "storeAs":"[chat-ads]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"affiliate links",
        "storeAs":"[chat-ads]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"website URLs",
        "storeAs":"[chat-ads]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other",
        "storeAs":"[chat-ads]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q33",
    "spaces":["m","c"],
    "position":["et",2],
    "q":"Who can post job listings?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"recruiters",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"Recruiters are permitted to post jobs, but please be respectful of everyone’s time and avoid repeated posts. If you’re coming here only to make a sales pitch, please don’t.",
      },
      {
        "type":"radio",
        "answerText":"nobody",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"We do not permit any job postings in the [name] [type]]",
      },
      {
        "type":"radio",
        "answerText":"anybody",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"If you are an active community member and you are personally hiring more people, you may post relevant job descriptions.",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q34",
    "spaces":["on","p"],
    "position":["et",3],
    "q":"Are you concerned about illegal activities happening in your space?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"Yes",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"Keep it legal: basically, don’t get anyone in trouble. Share only content that you own, do not share private or sensitive information, and don’t break the law. Sharing content or links to content that is illegal or violates any applicable local or national laws is not permitted and this includes defamatory statements and pirated software.",
      },
      {
        "type":"radio",
        "answerText":"No",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q35",
    "spaces":["p"],
    "position":["et",4],
    "q":"Are participants likely to request remote technical assistance from others in this space?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"Yes",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"Community posts might include advice on commands to run on your computer or any other actions for you to perform. This sort of advice is provided by community members as-is, without any liability. Consider any such advice carefully, and ask for clarification as needed; any potential damage or loss of data resulting from following advice is your own responsibility.",
      },
      {
        "type":"radio",
        "answerText":"No",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q36",
    "spaces":["e","p"],
    "position":["se",0],
    "q":"Should participants expect to see discussions or content related to any sensitive or potentially triggering topics?",
    "required":false,
    "policyEntry":"Participants in this space should expect to see potentially triggering discussions about the following topics: [topics]",
    "answers":[
      {
        "type":"checkbox",
        "answerText":"pornography",
        "storeAs":"[topics]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"harassment",
        "storeAs":"[topics]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"abuse",
        "storeAs":"[topics]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"torture",
        "storeAs":"[topics]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"rape",
        "storeAs":"[topics]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"sexual assault",
        "storeAs":"[topics]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"war",
        "storeAs":"[topics]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"checkbox",
        "answerText":"death",
        "storeAs":"[topics]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other",
        "storeAs":"[topics]",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":"Let people know ahead of time so they can prepare coping strategies."},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q37",
    "spaces":["e","p"],
    "position":["se",1],
    "q":"How should the presentation of sensitive topics be handled?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"checkbox",
        "answerText":"In educational or otherwise relevant context",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"This content is only appropriate within an educational or otherwise relevant context.",
      },
      {
        "type":"checkbox",
        "answerText":"Check beforehand",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"Please check this type of content with [name] before sharing publicly.",
      },
      {
        "type":"checkbox",
        "answerText":"Provide warnings",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"If you discuss difficult topics that may be traumatic for some, please provide warnings so people may choose to not enter into a conversation or plan coping strategies.",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q38",
    "spaces":["e","p"],
    "position":["se",2],
    "q":"Is sexual content and imagery permitted in this space?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"No",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"Use of nudity and/or sexual language and imagery is not appropriate for any [name] space.",
      },
      {
        "type":"radio",
        "answerText":"In educational or otherwise relevant context",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"Gratuitous or off-topic use of sexual language and imagery is not appropriate, but this content can be shared appropriately at [name] [type] within an educational or otherwise relevant context.",
      },
      {
        "type":"radio",
        "answerText":"Check beforehand",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"Gratuitous or off-topic use of sexual language and imagery is not appropriate, but this content can be shared appropriately within [name] [type], under specific restrictions. Please check this type of content with the community organisers or leaders before sharing publicly.",
      },
      {
        "type":"radio",
        "answerText":"Provide warnings",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"Gratuitous or off-topic use of sexual language and imagery is not appropriate, but this content can be shared appropriately within [name] [type] when it is preceded by a warning.",
      },
      {
        "type":"text",
        "answerText":"",
        "placeholder":"other",
        "storeAs":"",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q39",
    "spaces":["off"],
    "position":["sp",1],
    "q":"Can sponsors use sexualised imagery, activities or booth staff clothing to promote themselves?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"Yes",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
      {
        "type":"radio",
        "answerText":"No",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"Unless it is relevant to their product or otherwise appropriate for the context of the [[name]] event, exhibitors should not use sexualized images, activities, or other material and booth staff (including volunteers) should not use sexualized uniforms, or otherwise create a sexualized environment.",
      },
    ],
    "tips":[
      {"meaning":""},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q40",
    "spaces":["e","p"],
    "position":["be",2],
    "q":"Is this a space with a lot of tech folks?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"Yes",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"Additionally, we welcome people of all academic and professional backgrounds as well as levels of expertise, preferred operating system, programming language, or text editor.",
      },
      {
        "type":"radio",
        "answerText":"No",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":"Working in tech brings rivalries between people who prefer one OS, language or editor over another. These can go too far and become gatekeeping and unwelcoming to new participants."},
      {"more":["lorem ipsum"]}
    ]
  },
  {
    "isQuestion": true,
    "id":"q41",
    "spaces":["e"],
    "position":["be",3],
    "q":"Does the Chatham House Rule apply?",
    "required":false,
    "policyEntry":"",
    "answers":[
      {
        "type":"radio",
        "answerText":"Yes",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":'Chatham House Rules apply in all [name] spaces in order to encourage inclusive and open dialogue. The rule states: “When a meeting, or part thereof, is held under the Chatham House Rule, participants are free to use the information received, but neither the identity nor the affiliation of the speaker(s), nor that of any other participant, may be revealed.”',
      },
      {
        "type":"radio",
        "answerText":"No",
        "storeAs": "",
        "excludes":[],
        "includes":[],
        "policyEntry":"",
      },
    ],
    "tips":[
      {"meaning":"Chatham House Rule specifies that only the content of an event can be shared with those outside it, and must not be attributed to anyone specifically."},
      {"more":["lorem ipsum"]}
    ]
  },
]
